ontologies:
  modelCatalog:
    xmlUrl: https://mintproject.github.io/Mint-ModelCatalog-Ontology/release/1.2.0/ontology.xml
    prefix: sdm
    prefixUri: https://w3id.org/okn/o/sdm#
  softwareDescription:
    xmlUrl: https://knowledgecaptureanddiscovery.github.io/SoftwareDescriptionOntology/release/1.3.0/ontology.xml
    prefix: sd
    prefixUri: https://w3id.org/okn/o/sd#
name: modelcatalog
output_dir: outputs
openapi_base: modelcatalog_info.yaml

endpoint:
  url: https://endpoint.mint.isi.edu/modelCatalog-1.2.0
  prefix: https://w3id.org/okn/i/mint/
  graph_base: http://ontosoft.isi.edu:3030/modelCatalog-1.2.0/data/

firebase:
  key:
