#Name of the project
name: dbpedia_music

## OpenAPI Section
### Name, version and URL of the OpenAPI
### For more information about the section. Go to the official documentation
openapi:
  openapi: 3.0.1
  info:
    description: This is the API of the DBpedia Ontology
    title: DBpedia
    version: v1.3.0
  externalDocs:
    description: DBpedia
    url:  http://dbpedia.org/
  servers:
    - url: https://dbpedia.dbpedia.oba.isi.edu/v1.3.0
    - url: http://localhost:8080/v1.3.0

## Ontologies
### List of ontologies
ontologies:
  - https://tinyurl.com/dbpediaoba

## SPARQL information
endpoint:
  url: http://dbpedia.org/sparql
  prefix: http://dbpedia.org/resource
  graph_base: http://ontosoft.isi.edu:3030/modelCatalog-1.2.0/data/

## Filter the paths by methods
enable_get_paths: true
enable_post_paths: false
enable_delete_paths: false
enable_put_paths: false

## Select the classes to add in the API
classes:
  - http://dbpedia.org/ontology/Genre
  - http://dbpedia.org/ontology/Band
follow_references: false
